document.addEventListener('DOMContentLoaded',()=>{
 const galleries=[...document.querySelectorAll('.day-section .photo-gallery')]; if(!galleries.length)return;
 const lb=document.createElement('div'); lb.className='lightbox'; lb.setAttribute('role','dialog'); lb.setAttribute('aria-modal','true'); lb.innerHTML='<button class="lightbox-close" aria-label="Cerrar">×</button><button class="lightbox-prev" aria-label="Fotografía anterior">‹</button><img class="lightbox-image" alt=""><button class="lightbox-next" aria-label="Fotografía siguiente">›</button><div class="lightbox-counter" aria-live="polite"></div>'; document.body.appendChild(lb);
 const image=lb.querySelector('.lightbox-image'),counter=lb.querySelector('.lightbox-counter'); let gallery=null,index=0;
 function open(g,i){gallery=g;index=i;const imgs=[...g.querySelectorAll('img')],img=imgs[i];image.src=img.currentSrc||img.src;image.alt=img.alt||'';counter.textContent=`${i+1} / ${imgs.length}`;lb.classList.add('is-open');document.body.style.overflow='hidden'}
 function move(n){if(!gallery)return;const imgs=[...gallery.querySelectorAll('img')];index=(index+n+imgs.length)%imgs.length;open(gallery,index)}
 galleries.forEach(g=>g.querySelectorAll('.photo-frame').forEach((frame,i)=>{frame.addEventListener('click',()=>open(g,i));frame.tabIndex=0;frame.setAttribute('role','button');frame.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open(g,i)}})}));
 lb.querySelector('.lightbox-close').onclick=()=>{lb.classList.remove('is-open');document.body.style.overflow=''};lb.querySelector('.lightbox-prev').onclick=()=>move(-1);lb.querySelector('.lightbox-next').onclick=()=>move(1);lb.addEventListener('click',e=>{if(e.target===lb)lb.querySelector('.lightbox-close').click()});document.addEventListener('keydown',e=>{if(!lb.classList.contains('is-open'))return;if(e.key==='Escape')lb.querySelector('.lightbox-close').click();if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1)});
});
