(function(){
  'use strict';

  const API='https://anwdwhrybknczptrmzci.supabase.co/functions/v1/reviews-api';
  const HEADERS={'x-vc-client':'web'};

  const esc=(value='')=>String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const average=values=>{const nums=values.map(Number).filter(v=>Number.isFinite(v)&&v>=1&&v<=5);return nums.length?nums.reduce((a,b)=>a+b,0)/nums.length:null};
  const starsText=value=>'★'.repeat(Math.round(value||0))+'☆'.repeat(5-Math.round(value||0));
  const pct=value=>value?`${Math.max(0,Math.min(100,(value/5)*100))}%`:'0%';
  const fmtDate=value=>new Intl.DateTimeFormat('es-ES',{day:'numeric',month:'short',year:'numeric'}).format(new Date(value));

  function markup(title,type){
    const intro=type==='itinerary'?`¿Has seguido este itinerario? Cuéntanos tu experiencia y ayuda a otros viajeros.`:`¿Has visitado ${esc(title)}? Cuéntanos tu experiencia y ayuda a otros viajeros.`;
    return `<div class="vc-reviews-shell">
      <div class="vc-reviews-head"><div><span class="vc-reviews-kicker">COMUNIDAD VIAJERA</span><h2>¿QUÉ OPINAN OTROS VIAJEROS?</h2><p>Valoraciones reales de la comunidad de Viajando con Cabeza.</p></div></div>
      <div class="vc-reviews-summary" data-summary><div class="vc-score-card"><div class="vc-score-empty">CARGANDO VALORACIONES…</div><small>Un momento.</small></div><div class="vc-rating-bars" data-bars></div><div class="vc-review-benefits"><div class="vc-review-benefit"><div class="vc-review-benefit-icon">✓</div><div><b>Opiniones reales</b><span>De viajeros como tú</span></div></div><div class="vc-review-benefit"><div class="vc-review-benefit-icon">♙</div><div><b>Ayuda a otros viajeros</b><span>Comparte tu experiencia</span></div></div><div class="vc-review-benefit"><div class="vc-review-benefit-icon">♡</div><div><b>Tu opinión cuenta</b><span>Nos ayuda a mejorar</span></div></div></div></div>
      <div class="vc-reviews-list" data-list></div>
      <form class="vc-review-form" data-form novalidate>
        <div class="vc-review-form-title"><span>✎</span><div><h3>Deja tu valoración</h3><p>${intro}</p></div></div>
        <div class="vc-review-form-grid">
          <div class="vc-review-field"><label>Tu puntuación general <b>*</b></label><div class="vc-review-stars" data-stars="rating"></div><input type="hidden" name="rating" required></div>
          <div class="vc-review-field"><label>Valora diferentes aspectos <span>(opcional)</span></label><div class="vc-category-rating"><span>Destino</span><span class="vc-mini-stars" data-stars="rating_destination"></span></div><div class="vc-category-rating"><span>Gastronomía</span><span class="vc-mini-stars" data-stars="rating_food"></span></div><div class="vc-category-rating"><span>Transporte</span><span class="vc-mini-stars" data-stars="rating_transport"></span></div><div class="vc-category-rating"><span>Calidad-precio</span><span class="vc-mini-stars" data-stars="rating_value"></span></div></div>
          <div class="vc-review-field vc-comment-field"><label>Tu comentario <b>*</b></label><textarea name="comment" maxlength="2000" minlength="10" required placeholder="Cuéntanos tu experiencia, lo que más te gustó, tus consejos..."></textarea></div>
        </div>
        <div class="vc-review-bottom"><div><label>Tu nombre o alias <b>*</b></label><input name="name" maxlength="80" required placeholder="Ej. Laura M."></div><div><label>Tipo de viaje</label><select name="trip_type"><option value="">Selecciona...</option><option value="Pareja">Pareja</option><option value="Familia">Familia</option><option value="Amigos">Amigos</option><option value="En solitario">En solitario</option><option value="Trabajo">Trabajo</option></select></div><label class="vc-review-consent"><input type="checkbox" name="consent" required> He leído y acepto la política de comentarios</label><input class="vc-review-honeypot" name="website" tabindex="-1" autocomplete="off" aria-hidden="true"><button class="vc-review-submit" type="submit">ENVIAR VALORACIÓN</button></div>
        <div class="vc-review-note">ℹ Todas las valoraciones se revisan antes de publicarse para evitar spam y contenido inapropiado.</div><div class="vc-review-message" data-message role="status" aria-live="polite"></div>
      </form>
    </div>`;
  }

  function makeStars(container,input){for(let i=1;i<=5;i++){const btn=document.createElement('button');btn.type='button';btn.className='vc-star';btn.textContent='★';btn.dataset.value=i;btn.setAttribute('aria-label',`${i} estrella${i===1?'':'s'}`);btn.addEventListener('click',()=>{input.value=i;[...container.children].forEach((s,idx)=>s.classList.toggle('is-on',idx<i))});container.appendChild(btn)}}

  function renderSummary(root,reviews,title){const overall=average(reviews.map(r=>r.rating));const summary=root.querySelector('[data-summary]');const score=summary.querySelector('.vc-score-card');score.innerHTML=!reviews.length?`<div class="vc-score-empty">SIN VALORACIONES TODAVÍA</div><small>Sé la primera persona en valorar ${esc(title)}.</small>`:`<div class="vc-score"><strong>${overall.toFixed(1)}</strong><span>/ 5</span></div><div class="vc-score-stars">${starsText(overall)}</div><small>${reviews.length} valoración${reviews.length===1?'':'es'} publicada${reviews.length===1?'':'s'}</small>`;const metrics=[['Destino','rating_destination'],['Gastronomía','rating_food'],['Transporte','rating_transport'],['Calidad-precio','rating_value'],['Experiencia general','rating']];summary.querySelector('[data-bars]').innerHTML=metrics.map(([label,key])=>{const avg=average(reviews.map(r=>r[key]));return `<div class="vc-rating-row"><span>${label}</span><span class="vc-rating-bar"><i style="width:${pct(avg)}"></i></span><b>${avg?avg.toFixed(1):'—'}</b></div>`}).join('')}

  function renderList(root,reviews){const list=root.querySelector('[data-list]');if(!reviews.length){list.innerHTML='<div class="vc-reviews-empty"><strong>Aún no hay comentarios publicados</strong><span>Cuando aprobemos las primeras valoraciones aparecerán aquí.</span></div>';return}list.innerHTML=`<div class="vc-reviews-list-head"><h3>Comentarios recientes</h3><span>${reviews.length} publicados</span></div><div class="vc-review-cards">${reviews.map(r=>`<article class="vc-review-card"><div class="vc-review-card-top"><div><strong>${esc(r.name)}</strong><span>${esc(r.trip_type||'Viajero/a')} · ${fmtDate(r.created_at)}</span></div><div class="vc-card-score"><b>${Number(r.rating).toFixed(1)}</b><span>${starsText(r.rating)}</span></div></div>${r.comment?`<p>${esc(r.comment)}</p>`:''}</article>`).join('')}</div>`}

  async function load(root,pageId,pageType,title){try{const qs=new URLSearchParams({page_id:pageId,page_type:pageType});const res=await fetch(`${API}?${qs}`,{headers:HEADERS});if(!res.ok)throw new Error();const data=await res.json();const reviews=data.reviews||[];renderSummary(root,reviews,title);renderList(root,reviews)}catch(e){renderSummary(root,[],title);renderList(root,[]);const msg=root.querySelector('[data-message]');msg.textContent='No hemos podido cargar las valoraciones ahora mismo.';msg.classList.add('is-error')}}

  function bind(root,pageId,pageType){const form=root.querySelector('[data-form]');form.querySelectorAll('[data-stars]').forEach(group=>{const name=group.dataset.stars;let input=form.elements[name];if(!input){input=document.createElement('input');input.type='hidden';input.name=name;form.appendChild(input)}makeStars(group,input)});form.addEventListener('submit',async e=>{e.preventDefault();const msg=form.querySelector('[data-message]');const btn=form.querySelector('.vc-review-submit');msg.textContent='';msg.className='vc-review-message';if(form.elements.website.value)return;if(!form.elements.rating.value){msg.textContent='Selecciona una puntuación general de 1 a 5 estrellas.';msg.classList.add('is-error');return}if(!form.reportValidity())return;const last=Number(localStorage.getItem('vc_last_review')||0);if(Date.now()-last<60000){msg.textContent='Espera un minuto antes de enviar otra valoración.';msg.classList.add('is-error');return}const payload={page_id:pageId,page_type:pageType,name:form.elements.name.value.trim(),trip_type:form.elements.trip_type.value||null,rating:Number(form.elements.rating.value),rating_destination:form.elements.rating_destination.value?Number(form.elements.rating_destination.value):null,rating_food:form.elements.rating_food.value?Number(form.elements.rating_food.value):null,rating_transport:form.elements.rating_transport.value?Number(form.elements.rating_transport.value):null,rating_value:form.elements.rating_value.value?Number(form.elements.rating_value.value):null,comment:form.elements.comment.value.trim(),website:form.elements.website.value};btn.disabled=true;btn.textContent='ENVIANDO…';try{const res=await fetch(API,{method:'POST',headers:{...HEADERS,'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!res.ok)throw new Error();localStorage.setItem('vc_last_review',String(Date.now()));form.reset();form.querySelectorAll('.vc-star').forEach(s=>s.classList.remove('is-on'));msg.textContent='¡Gracias! Tu valoración se ha enviado correctamente y aparecerá cuando la revisemos.';msg.classList.add('is-success')}catch(e){msg.textContent='No hemos podido enviar tu valoración. Inténtalo de nuevo en unos minutos.';msg.classList.add('is-error')}finally{btn.disabled=false;btn.textContent='ENVIAR VALORACIÓN'}})}

  function init(root){const pageId=(root.dataset.reviewPage||'').trim();const pageType=(root.dataset.reviewType||'guide').trim();const title=(root.dataset.reviewTitle||pageId||'esta guía').trim();if(!pageId||!['guide','itinerary'].includes(pageType))return;root.innerHTML=markup(title,pageType);bind(root,pageId,pageType);load(root,pageId,pageType,title)}

  document.addEventListener('DOMContentLoaded',()=>document.querySelectorAll('[data-review-page]').forEach(init));
})();
