(function(){
  const path=window.location.pathname;
  const isRoot=/\/(web\/)?$/.test(path)||path.endsWith('/index.html')&&!/(destinos|itinerarios|planifica|nosotros|contacto)\//.test(path);
  const base=isRoot?'':'../';
  const section=isRoot?'inicio':(path.match(/\/(destinos|itinerarios|planifica|nosotros|contacto)\//)||[])[1]||'';
  const instagram='https://www.instagram.com/viajandoconcabeza/';
  const items=[['inicio','INICIO',base+'index.html'],['destinos','DESTINOS',base+'destinos/index.html'],['itinerarios','ITINERARIOS',base+'itinerarios/index.html'],['planifica','PLANIFICA',base+'planifica/index.html'],['nosotros','NOSOTROS',base+'nosotros/index.html'],['contacto','CONTACTO',base+'contacto/index.html']];
  const iconInstagram='<svg viewBox="0 0 24 24"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" fill="currentColor" stroke="none"/></svg>';
  const iconTikTok='<svg viewBox="0 0 24 24"><path d="M14.5 4v10.1a4.4 4.4 0 1 1-3.7-4.3v3a1.7 1.7 0 1 0 1 1.6V4h2.7c.3 2.3 1.7 3.8 4.2 4.2v2.7a7.6 7.6 0 0 1-4.2-1.6"/></svg>';
  const iconYoutube='<svg viewBox="0 0 24 24"><path d="M21 8.2a3 3 0 0 0-2.1-2.1C17 5.5 12 5.5 12 5.5s-5 0-6.9.6A3 3 0 0 0 3 8.2 31 31 0 0 0-.5 3.8 31 31 0 0 0 .5 3.8 3 3 0 0 0 2.1 2.1c1.9.6 6.9.6 6.9.6s5 0 6.9-.6a3 3 0 0 0 2.1-2.1 31 31 0 0 0 .5-3.8 31 31 0 0 0-.5-3.8Z"/><path d="m10 9 5 3-5 3Z" fill="currentColor"/></svg>';
  const html='<header class="shared-header"><div class="shared-nav"><a class="shared-brand" href="'+base+'index.html"><img src="'+base+'assets/branding/logo-viajando-con-cabeza.svg" alt="Viajando con Cabeza"></a><nav class="shared-menu">'+items.map(i=>'<a class="'+(section===i[0]?'active':'')+'" href="'+i[2]+'">'+i[1]+'</a>').join('')+'</nav><div class="shared-social"><a href="'+instagram+'" target="_blank" rel="noopener" aria-label="Instagram">'+iconInstagram+'</a><span aria-label="TikTok">'+iconTikTok+'</span><span aria-label="YouTube">'+iconYoutube+'</span></div></div></header>';
  const old=document.querySelector('.site-header,.page-header,.shared-header'); if(old) old.outerHTML=html; else document.body.insertAdjacentHTML('afterbegin',html);
  if(!document.getElementById('shared-header-style')){const s=document.createElement('style');s.id='shared-header-style';s.textContent='.shared-header{height:50px;background:#fff;border-bottom:1px solid #eee;position:sticky;top:0;z-index:1000;width:100%;font-family:"DM Sans",sans-serif}.shared-nav{width:min(1180px,calc(100% - 48px));height:50px;margin:auto;display:grid;grid-template-columns:138px 1fr 92px;align-items:center;column-gap:16px}.shared-brand{display:flex;align-items:center;width:134px;height:44px}.shared-brand img{display:block;width:128px;height:42px;object-fit:contain;object-position:left center}.shared-menu{display:flex;align-items:center;justify-content:center;gap:25px;font-size:9.3px;font-weight:800}.shared-menu a{color:#111315;text-decoration:none;padding:18px 0 16px;position:relative}.shared-menu a.active:after{content:"";position:absolute;left:0;right:0;bottom:9px;height:2px;background:#ef7168}.shared-social{display:flex;justify-content:flex-end;align-items:center;gap:12px}.shared-social a,.shared-social span{display:grid;place-items:center;width:22px;height:22px;color:#0f1113}.shared-social svg{width:20px;height:20px;fill:none;stroke:currentColor;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}@media(max-width:720px){.shared-header{height:auto;position:relative}.shared-nav{width:calc(100% - 28px);height:auto;grid-template-columns:1fr auto;padding:4px 0}.shared-brand{width:122px;height:41px}.shared-brand img{width:118px;height:39px}.shared-menu{grid-column:1/3;order:3;overflow-x:auto;justify-content:flex-start;gap:18px;padding:2px 0 1px}.shared-menu a{padding:4px 0;white-space:nowrap}.shared-menu a.active:after{bottom:0}.shared-social{display:none}}';document.head.appendChild(s);}
})();